name: rlogic
description: Develop logic thinking

publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share: ^2.0.4
  font_awesome_flutter: ^9.1.0
  function_tree: ^0.8.12
  easy_rich_text: ^0.5.7
  url_launcher: ^6.0.9
  google_mobile_ads: ^0.13.0
  trotter:  ^2.0.0-dev.1
  carousel_slider: ^4.0.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.2
  shared_preferences: ^2.0.7
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.0.3
  in_app_purchase: ^1.0.8
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.3
  google_sign_in: ^5.1.0
  purchases_flutter: ^3.4.5
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/icons8-idea.png
    - assets/images/SkyScrapers/
    - assets/images/Bulls&Cows/
    - assets/images/4Digits/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic